from .testcustomers import TestCustomers
from .testlogin import TestLogin
from .testorderproducts import TestOrderProducts
from .testorders import TestOrders
from .testpaymenttypes import TestPaymentTypes
from .testproducts import TestProducts
from .testproducttypes import TestProductTypes
from .testregister import TestRegister
from .testusers import TestUser
